services:
  basebook:
    build: .
    image: basebook
    container_name: basebook
    ports:
      - "8080:8080"
    volumes:
      - basebook_data:/data
    networks:
      - basebook_network

volumes:
  basebook_data:

networks:
  basebook_network:
