services:
  basebook:
    build: .
    image: basebook
    container_name: basebook
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - basebook_data:/app/dados
    networks:
      - basebook_network

volumes:
  basebook_data:

networks:
  basebook_network:
